/*******************************************************************************
  Multipurpose FIFO Source Library

  Summary:
    FIFO wrapper for EZBL_vsprintf() against an EZBL_FIFO

  *******************************************************************************/

// DOM-IGNORE-BEGIN
/*******************************************************************************
  Copyright (C) 2017 Microchip Technology Inc.

  MICROCHIP SOFTWARE NOTICE AND DISCLAIMER:  You may use this software, and any
  derivatives created by any person or entity by or on your behalf, exclusively
  with Microchip's products.  Microchip and its licensors retain all ownership
  and intellectual property rights in the accompanying software and in all
  derivatives here to.

  This software and any accompanying information is for suggestion only.  It
  does not modify Microchip's standard warranty for its products.  You agree
  that you are solely responsible for testing the software and determining its
  suitability.  Microchip has no obligation to modify, test, certify, or
  support the software.

  THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER
  EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED
  WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR
  PURPOSE APPLY TO THIS SOFTWARE, ITS INTERACTION WITH MICROCHIP'S PRODUCTS,
  COMBINATION WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION.

  IN NO EVENT, WILL MICROCHIP BE LIABLE, WHETHER IN CONTRACT, WARRANTY, TORT
  (INCLUDING NEGLIGENCE OR BREACH OF STATUTORY DUTY), STRICT LIABILITY,
  INDEMNITY, CONTRIBUTION, OR OTHERWISE, FOR ANY INDIRECT, SPECIAL, PUNITIVE,
  EXEMPLARY, INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, FOR COST OR EXPENSE OF
  ANY KIND WHATSOEVER RELATED TO THE SOFTWARE, HOWSOEVER CAUSED, EVEN IF
  MICROCHIP HAS BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.
  TO THE FULLEST EXTENT ALLOWABLE BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL
  CLAIMS IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF
  FEES, IF ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.

  MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE
  TERMS.
*******************************************************************************/
// DOM-IGNORE-END

#include <stdio.h>
#include <stdarg.h>
#include "../ezbl.h"

/**
 * Prints formatted text to an EZBL_FIFO using a variable length argument list.
 *
 * This function internally calls EZBL_vsprintf(). See the compiler libraries
 * printf() documentation for full formatting options.
 *
 * This function can internally handle at most the FIFO's defined RAM size +
 * 32 characters. Results are undefined (and may potentially corrupt the stack)
 * if the format string and parameters result in a larger amount of data being
 * generated.
 *
 * @param *fifo Pointer to an EZBL_FIFO to write the output to. If the FIFO
 *              is full or becomes full, any extra data generated by the printf
 *              operation is thrown away without blocking for the FIFO to
 *              potentially drain.
 * @param *format Constant formatting string for printf(). See compiler library
 *                documentation on printf() for full details.
 * @param ...     Zero or more additional variables to be printed when
 *                encountered in the format string.
 *
 * @return Number of bytes successfully generated and written to the FIFO. This
 *         will be less than the number of bytes the printf() call should have
 *         generated if the FIFO becomes full.
 */
unsigned int EZBL_FIFOprintf(EZBL_FIFO *fifo, const char *format, ...)
{
    char *stackBuf;
    unsigned int printLen;
    va_list args;

    // Allocate RAM on the stack to hold the output string. Since vsprintf() can
    // generate an unknown amount of data, stack overflow is intrinsically
    // possible. However, by allocating the full FIFO's size + 32 guard band, we
    // can at least have a good assurance that FIFO sizes that are appropriate
    // for the called print operation will succeed without risking data
    // corruption. This also allows users to tune the max data length externally
    // by declaring a bigger FIFO memory.
    stackBuf = __builtin_alloca(fifo->fifoSize+32u);

    va_start(args, format);    // Initialize variable arguments list
    printLen = EZBL_vsprintf(stackBuf, format, args);
    va_end(args);              // Clean up variable arguments list (does nothing in GNU C)

    return EZBL_FIFOWrite(fifo, stackBuf, printLen);
}
